trigger:
  - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'install dependencies'

  - script: |
      tsc --target ES6 --strict true --project tsconfig.json
    displayName: 'typescript compilation to ES6'

  - script: npm run CItest
    displayName: 'run automated tests'

  - script: npm run build
    displayName: 'create build to deploy'

  - task: DeleteFiles@1
    displayName: Delete `node_modules/.bin` folder from staging directory
    inputs:
      sourceFolder: $(Build.StagingDirectory)
      contents: node_modules/.bin

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      replaceExistingArchive: true

  - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    artifact: drop
